[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyproject_base"
description = "project description"
version = "0.1.0"
dependencies = [
]

authors = [
    {name = "the-citto", email = "my.email@domain.com"}
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: MIT",
    "Operating System :: Linux"
]

[project.optional-dependencies]
tests = ["pytest"]
dev = [
    "pytest",
    "ipython",
]

[project.scripts]
pyproject_base = "pyproject_base:main"


[tool.setuptools]
package-dir = {"" = "python"}


[tool.pyright]
venvPath = "."
venv = ".venv"

include = [
    "python",
    "tests",
]
exclude = [
    "__pycache__",
    ".git",
    ".venv",
    "_old",
    "_tmp",
]

[tool.ruff]
exclude = [
    "__pycache__",
    ".git",
    ".venv",
    "_old",
    "_tmp",
]
line-length = 120
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = [
    "ALL"
]
ignore = [
    # This rule is deprecated and will be removed in a future release.
    "ANN101", # Missing type annotation for `self` in method
    "ERA001", # Found commented-out code
    "TD003", # Missing issue link on the line following this TODO
]

[tool.ruff.isort]
known-first-party = ["python"]

