
line-length = 120

[lint]
select = ["ALL"]
ignore = [
    "D203", # `one-blank-line-before-class`
    "D213", # `multi-line-summary-first-line`
    "ERA001", # Found commented-out code
] # (D203) mutually exclusive with (D211) - (D212) mutually exclusive with (D213)

[lint.per-file-ignores]
"tests/**/*.py" = [
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "PLR2004", # Magic value used in comparison
    "S101", # Use of `assert`
]


